@startuml
participant 운영자

activate 운영자
운영자 -> 시스템 : 1. 주문 데이터 요청

activate 시스템
activate DBMS
시스템 -> DBMS : 1.1 애그리거트 데이터 로딩
DBMS -> 시스템 : 1.2 데이터 리턴 (버전 A 포함)
deactivate DBMS
시스템 -> 운영자 : 1.3 데이터 제공 (버전 A 포함)
deactivate 시스템

운영자 -> 시스템 : 2. 배송 상태 변경 요청 (버전 A포함)
activate 시스템
activate DBMS
시스템 -> DBMS : 2.1 애그리거트 데이터 로딩
DBMS -> 시스템 : 2.1.1 데이터 리턴(버전 B 포함)
deactivate DBMS


alt 버전 A!= 버전 B
    시스템 -> 운영자 : 2.1.2 수정할 수 없는 에러 응답
else 버전 A == 버전 B
    시스템 -> 시스템 : 2.1.3 애그리거트 배송 상태 변경
    activate 시스템
    deactivate 시스템
    시스템 -> DBMS : 2.1.4 쿼리실행
    activate DBMS
    시스템 -> 운영자 : 2.1.5 결과 응답
    deactivate DBMS
    
end 
deactivate 시스템
@enduml


@startuml
participant 운영자

운영자 -> 시스템 : 1. 주문 정보 조회
activate 시스템 
시스템 -> 운영자 : 1.1 정보 제공(배송지 포함) 
시스템 -> 고객 : 2. 주문 정보 변경 폼 요청
고객 -> 시스템 : 2.1 정보 수정 폼 제공
시스템 -> 고객 : 3. 배송지 변경 요청
고객 -> 시스템 : 3.1 성공 결과 화면
운영자 -> 시스템 : 4. 배송 상태 변겨 요청
시스템 -> 운영자 : 4.1 성공 결과 화면
@enduml